/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as BlogArticleIdRouteImport } from './routes/blog_.$articleId'
import { Route as PortfolioProjectIdRouteImport } from './routes/portfolio_.$projectId'
import { Route as ServicesServiceSlugRouteImport } from './routes/services_.$serviceSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogArticleIdRoute = BlogArticleIdRouteImport.update({
  id: '/blog_/$articleId',
  path: '/blog/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioProjectIdRoute = PortfolioProjectIdRouteImport.update({
  id: '/portfolio_/$projectId',
  path: '/portfolio/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/services_/$serviceSlug',
  path: '/services/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$articleId': typeof BlogArticleIdRoute
  '/portfolio/$projectId': typeof PortfolioProjectIdRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRoute
  '/api/chat': typeof ApiChatRoute
  '/blog_/$articleId': typeof BlogArticleIdRoute
  '/portfolio_/$projectId': typeof PortfolioProjectIdRoute
  '/services_/$serviceSlug': typeof ServicesServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/quote'
    | '/services'
    | '/api/chat'
    | '/blog/$articleId'
    | '/portfolio/$projectId'
    | '/services/$serviceSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/quote'
    | '/services'
    | '/api/chat'
    | '/blog/$articleId'
    | '/portfolio/$projectId'
    | '/services/$serviceSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/portfolio'
    | '/quote'
    | '/services'
    | '/api/chat'
    | '/blog_/$articleId'
    | '/portfolio_/$projectId'
    | '/services_/$serviceSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogArticleIdRoute: typeof BlogArticleIdRoute
  PortfolioProjectIdRoute: typeof PortfolioProjectIdRoute
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$articleId': {
      id: '/blog_/$articleId'
      path: '/blog/$articleId'
      fullPath: '/blog/$articleId'
      preLoaderRoute: typeof BlogArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio_/$projectId': {
      id: '/portfolio_/$projectId'
      path: '/portfolio/$projectId'
      fullPath: '/portfolio/$projectId'
      preLoaderRoute: typeof PortfolioProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services_/$serviceSlug': {
      id: '/services_/$serviceSlug'
      path: '/services/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRoute,
  ApiChatRoute: ApiChatRoute,
  BlogArticleIdRoute: BlogArticleIdRoute,
  PortfolioProjectIdRoute: PortfolioProjectIdRoute,
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
